apiVersion: kustomize.config.k8s.io/v1beta1		## kubectl explain Kustomization korle betav1 ase na, but dite hobe ##
kind: Kustomization
metadata:
  name: fluxcdkustomization
  namespace: fluxcdtutorial
resources:
  - deployment.yaml
  - service.yaml
