---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-monitoring
  namespace: fluxcdtutorial
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/fluxcd/flux2-monitoring-example
