apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-token
  namespace: fluxcdtutorial
spec:
  encryptedData:
    token: AgBAIDKrK3xmBiHrFRkQ/Vie1e2fEOlwOOVzNOTBuSDcrvtMaXAibQlaVYxPIP4dtxUF11SYO5lkpUM/penJU0emYeGFweAqFyto8bzFX/Ionw0SjHwlIACjV5VZA2xy+3eKLoL1YiwfLQfaepuqA21utgrEjtrmHBr5KWrAYYOi4t25L9VmhbBqSk/fjisGiYZrbK/9fYis+2A5LBLuWenz07fANXnK75YtVc6+19Pr9pUFr7j3mL270ilwmaHCCtc9eaxVu4/DLK9oJnaDaezaXHJWeMJzzWBlM2xpZzyZUJZzBLlEoLlCoKzRhZoIZdUgp3CsSio1UV22boa6IXlkcZ20RfbyOWtIBhI9bBJyxQhnY2ALcjaa3z1af1i2uzM8VrkImmr/hECJR4mUzQ8Vcg1npITSvqmr/3/0cserNIQlgwVUk4O89h+/4YnBDdfY/hUFt26qG25r2oOIfiVSr7WMOZU834zHBX6+qNsohLdsreh2WRqSOMl2L5FH22p+V8p5p+4BE70nsgKyMWhawFG8HI1daQLJ32dS/RnK0uFhrNuTCXiCn74+Ako0wVWfRuP60Cf9OMB4wPj3CjZHG44JUUeB4M5lMrNGp3D2oSyrA5CAeax8yDgv/8kkTFHE4ARlM6mrs9WFNSG4nBHUAJCDDTTvv/JkXtgZp+EtlNwxVEivkjbakoNqmzTzxjVtf+fCa11Fxq45USNqvLAnVpzXzYDGcoedmnzPW7/71jBzOoaLuLV5
  template:
    metadata:
      creationTimestamp: null
      name: github-token
      namespace: fluxcdtutorial
    type: Opaque

