apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github
  namespace: fluxcdtutorial
spec:
  encryptedData:
    token: AgBbd+HD0IJu/Ez0NWjckTHhv33oJaDw3/VX3fK2+lJPzdvW/Uqk59Y9KSDnNvHX1Z3dWJz6rdypub5nQgwOdcs6Sud9TNc76f9oGYMJ4stYz+Gu9hVD2uFSurwSY2icxNP7aByI3qqZkf8VcZP+kMbj6oLE+WiBX2JNLmH06X9kxBQJCinorXrmjg2m1RivyfRM0tnVaT1d8O4BxSShHlfO7ztIDPw54eytS6ikTzOW2s7oJp/ASo1+wvyxH+Exm+eGRE71asX+HCULQLEucH8rCoQqO1RfAlaI9tmUlWZTHeSs18nLW9+Uu0Bf6t9EfanBKbQu512V+aSFr4Lon1qCTmZRCUjBkH14MF8fK8oVG6JBz+wlM8Cr+qAWz6ayLitj0tsCiPtoPoWQeG0ix3cVusQm2Y/IVxrnuQ9v6PLLI+mzordFj2vJp+8MwgLLvrw0WnXjvIl4aCKa7O+ngC6txoviiG8oiFRZw9tmz9ZFB+elC6cxLybkzoeABR0QQSQShAGkT2N8OX0QOLEsEsG6Bn4RfioKWBGxi5oecFoYDoXoGceWpq0EjUPPSIUJAzRkhiFRK4SvUVgQOMJhnvRLnyX4fdhAr/pCAEETRqpD4ZvHe3Pi9FAiUWu9XKG9D3Q1DWGv1Wz6XenyffwdFbtVa1Y/byFTqSdxIt22KvfR3Gu+7nRIw22JxWU2mrnNYKZm1H8EyFWtq9dyDtEpK+sesl4cmth9wVN0BkFVrEkJPk1psaF8cYRk
  template:
    metadata:
      creationTimestamp: null
      name: github
      namespace: fluxcdtutorial
    type: Opaque

